Update qualys.yml

diff --git a/.github/workflows/qualys.yml b/.github/workflows/qualys.yml
--- a/.github/workflows/qualys.yml
+++ b/.github/workflows/qualys.yml
@@ -18,7 +18,7 @@ jobs:
                 xml_content='<ServiceRequest>
                 <data>
                 <WebApp>
-                <url></url>
+                <url>{{ vars.SERVICE_URL }}</url>
                 </WebApp>
                 </data>
                 </ServiceRequest>'
@@ -31,8 +31,14 @@ jobs:
              
           - name: Update WAS App
             run: |
-              curl -u "${{ vars.QUALYS_USERNAME }}:${{ secrets.QUALYS_PASSWORD }}" -H "content-type: text/xml" -X "POST" --data-binary @file.xml "${{ vars.API_SERVER }}/qps/rest/3.0/update/was/webapp/${{ vars.WEBAPP_ID }}"
-    
+              $response=(curl --write-out "%{http_code}" --silent --output /dev/null  -u "${{ vars.QUALYS_USERNAME }}:${{ secrets.QUALYS_PASSWORD }}" -H "content-type: text/xml" -X "POST" --data-binary @file.xml "${{ vars.API_SERVER }}/qps/rest/3.0/update/was/webapp/${{ vars.WEBAPP_ID }}")
+              if [ "$response" -ne 200 ]; then
+                echo "Error: Received status code $response"
+                exit 1  # This stops the pipeline if the status code is not 200
+              else
+                echo "Success: Received status code $response"
+              fi
+              
           - name: Qualys WAS scan action step
             uses: Qualys/github-action-qwas@main
             id: was
